# Generated by Django 2.0.7 on 2018-07-05 03:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Escolaridade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escolaridade', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estado_Civil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_civil', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Grupo_Pequeno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lider_Grupo_Pequeno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obs', models.TextField(blank=True, null=True)),
                ('grupo_pequeno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secretariaapp.Grupo_Pequeno')),
            ],
        ),
        migrations.CreateModel(
            name='Lider_Ministerio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obs', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Membro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=100)),
                ('data_situacao', models.DateField(blank=True, null=True)),
                ('data_nascimento', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('naturalidade', models.CharField(blank=True, max_length=30)),
                ('cpf', models.CharField(blank=True, max_length=11)),
                ('rg', models.CharField(blank=True, max_length=15)),
                ('endereco', models.CharField(blank=True, max_length=50)),
                ('n', models.CharField(blank=True, max_length=10)),
                ('bairro', models.CharField(blank=True, max_length=50)),
                ('cidade', models.CharField(max_length=50)),
                ('cep', models.CharField(blank=True, max_length=10)),
                ('telefone_celular', models.CharField(blank=True, max_length=15)),
                ('telefone_residencial', models.CharField(blank=True, max_length=15)),
                ('telefone_comercial', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('nome_responsavel', models.CharField(blank=True, max_length=100)),
                ('nome_conjuge', models.CharField(blank=True, max_length=100)),
                ('data_casascimento', models.DateField(blank=True, null=True)),
                ('numero_filhos', models.PositiveIntegerField(default=0)),
                ('filho1', models.CharField(blank=True, max_length=100)),
                ('data_nascimento_filho1', models.DateField(blank=True, null=True)),
                ('filho2', models.CharField(blank=True, max_length=100)),
                ('data_nascimento_filho2', models.DateField(blank=True, null=True)),
                ('filho3', models.CharField(blank=True, max_length=100)),
                ('data_nascimento_filho3', models.DateField(blank=True, null=True)),
                ('outros_filhos', models.TextField(blank=True)),
                ('profisao', models.CharField(blank=True, max_length=50)),
                ('economicamente_ativo', models.BooleanField(default=False)),
                ('data_conversao', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('data_batismo', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('igreja_batismo', models.CharField(blank=True, max_length=50)),
                ('pastor', models.CharField(blank=True, max_length=100)),
                ('data_chegada_na_elshaday', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('ministerios_que_deseja_participar', models.CharField(blank=True, max_length=100)),
                ('participa_grupo_pequeno', models.BooleanField(default=False)),
                ('obs', models.TextField(blank=True)),
                ('escolaridade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='secretariaapp.Escolaridade')),
                ('estado_civil', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='secretariaapp.Estado_Civil')),
                ('grupo_pequeno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='secretariaapp.Grupo_Pequeno')),
            ],
        ),
        migrations.CreateModel(
            name='Ministerio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('areas_atuacao', models.CharField(blank=True, max_length=100)),
                ('obs', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Obreiro_Ministerio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obs', models.TextField(blank=True, null=True)),
                ('ministerio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secretariaapp.Ministerio')),
                ('obreiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obreiro', to='secretariaapp.Membro')),
            ],
        ),
        migrations.CreateModel(
            name='Origem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem', models.CharField(max_length=30, unique=True)),
                ('descricao', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('gerenciar_Membros', models.BooleanField(default=False)),
                ('gerenciar_Grupos_Pequenos', models.BooleanField(default=False)),
                ('gerenciar_Ministerios', models.BooleanField(default=False)),
                ('gerenciar_Relatorios', models.BooleanField(default=False)),
                ('gerenciar_Usuarios', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexo', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Situacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situacao', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Uf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(max_length=2, unique=True)),
                ('estado', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='membro',
            name='origem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='secretariaapp.Origem'),
        ),
        migrations.AddField(
            model_name='membro',
            name='sexo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='secretariaapp.Sexo'),
        ),
        migrations.AddField(
            model_name='membro',
            name='situacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='secretariaapp.Situacao'),
        ),
        migrations.AddField(
            model_name='membro',
            name='uf_endereco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uf_endereco', to='secretariaapp.Uf'),
        ),
        migrations.AddField(
            model_name='membro',
            name='uf_nascimento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='uf_nascimento', to='secretariaapp.Uf'),
        ),
        migrations.AddField(
            model_name='lider_ministerio',
            name='ministerio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secretariaapp.Ministerio'),
        ),
        migrations.AddField(
            model_name='lider_ministerio',
            name='nome_lider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nome_lider', to='secretariaapp.Membro'),
        ),
        migrations.AddField(
            model_name='lider_grupo_pequeno',
            name='lider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lider', to='secretariaapp.Membro'),
        ),
    ]
