# Generated by Django 2.0.7 on 2019-04-24 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretariaapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trilha_Discipulado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trilha_discipulado', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='membro',
            name='trilha_discipulado',
            field=models.ManyToManyField(to='secretariaapp.Trilha_Discipulado'),
        ),
    ]
