# Generated by Django 2.0.7 on 2019-05-03 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretariaapp', '0005_auto_20190424_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='data_recuperar',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='recuperar',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
