# Generated by Django 2.0.7 on 2019-05-03 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretariaapp', '0006_auto_20190503_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='recuperar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
