# Generated by Django 2.0.7 on 2019-05-09 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secretariaapp', '0007_auto_20190503_1358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membro',
            old_name='data_casascimento',
            new_name='data_casamento',
        ),
    ]
