# Generated by Django 2.0.7 on 2019-05-11 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretariaapp', '0008_auto_20190509_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='membro',
            name='ministerios',
            field=models.ManyToManyField(blank=True, to='secretariaapp.Ministerio'),
        ),
    ]
