# Generated by Django 2.0.7 on 2019-05-11 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretariaapp', '0009_membro_ministerios'),
    ]

    operations = [
        migrations.AddField(
            model_name='membro',
            name='ministerios_que_lidera',
            field=models.ManyToManyField(blank=True, related_name='lider_ministario', to='secretariaapp.Ministerio'),
        ),
    ]
