# Generated by Django 2.0.7 on 2019-05-12 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secretariaapp', '0011_membro_grupos_pequenos_que_lidera'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lider_grupo_pequeno',
            name='grupo_pequeno',
        ),
        migrations.RemoveField(
            model_name='lider_grupo_pequeno',
            name='lider',
        ),
        migrations.RemoveField(
            model_name='lider_ministerio',
            name='ministerio',
        ),
        migrations.RemoveField(
            model_name='lider_ministerio',
            name='nome_lider',
        ),
        migrations.RemoveField(
            model_name='obreiro_ministerio',
            name='ministerio',
        ),
        migrations.RemoveField(
            model_name='obreiro_ministerio',
            name='obreiro',
        ),
        migrations.DeleteModel(
            name='Lider_Grupo_Pequeno',
        ),
        migrations.DeleteModel(
            name='Lider_Ministerio',
        ),
        migrations.DeleteModel(
            name='Obreiro_Ministerio',
        ),
    ]
